//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "vault_owner")]
pub enum VaultOwner {
    #[sea_orm(string_value = "Group")]
    Group,
    #[sea_orm(string_value = "User")]
    User,
}
#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "website_match_detection"
)]
pub enum WebsiteMatchDetection {
    #[sea_orm(string_value = "contains")]
    Contains,
    #[sea_orm(string_value = "ends_with")]
    EndsWith,
    #[sea_orm(string_value = "exact")]
    Exact,
    #[sea_orm(string_value = "host")]
    Host,
    #[sea_orm(string_value = "regex")]
    Regex,
    #[sea_orm(string_value = "starts_with")]
    StartsWith,
}
