//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.12

use sea_orm::entity::prelude::*;
use serde::Serialize;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize)]
#[sea_orm(table_name = "vault_folder")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub folder_id: Uuid,
    pub vault_id: Uuid,
    pub parent_folder_id: Option<Uuid>,
    pub name: String,
    pub icon_url: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::vault::Entity",
        from = "Column::VaultId",
        to = "super::vault::Column::VaultId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Vault,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentFolderId",
        to = "Column::FolderId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::vault_item::Entity")]
    VaultItem,
}

impl Related<super::vault::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Vault.def()
    }
}

impl Related<super::vault_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::VaultItem.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
